stages:
  - build
  - deploy

Build Prod:
  stage: build
  image: atnartur/docker:latest
  only:
    - main
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml push

Deploy Prod:
  stage: deploy
  image: atnartur/docker:latest
  only:
    - main
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prod.yml up -d
